#!/usr/bin/env perl
package TAEB::Knowledge::Item::Weapon;
use MooseX::Singleton;

has list => (
    is      => 'ro',
    isa     => 'HashRef',
    lazy    => 1,
    default => sub {
        my $weapons = {
            'Cleaver' => {
                artifact => 1,
                'sdam'   => 'd8+d6+d4',
                'ldam'   => '2d6+2d4',
                'tohit'  => 'd3',
                'hands'  => 2,
                'weight' => 120,
                'type'   => 'iron',
            },
            'Demonbane' => {
                artifact => 1,
                'sdam'   => 'd8',
                'ldam'   => 'd12',
                'tohit'  => 'd5',
                'hands'  => 1,
                'weight' => 40,
                'type'   => 'iron',
            },
            'Dragonbane' => {
                artifact => 1,
                'sdam'   => '2d4',
                'ldam'   => 'd6+1',
                'tohit'  => 'd5',
                'hands'  => 1,
                'weight' => 40,
                'type'   => 'iron',
            },
            'Excalibur' => {
                artifact => 1,
                'sdam'   => 'd8+d10',
                'ldam'   => 'd12+d10',
                'tohit'  => 'd5',
                'hands'  => 1,
                'weight' => 40,
                'type'   => 'iron',
            },
            'Fire Brand' => {
                artifact => 1,
                'sdam'   => 'd8',
                'ldam'   => 'd12',
                'tohit'  => 'd5',
                'hands'  => 1,
                'weight' => 40,
                'type'   => 'iron',
            },
            'Frost Brand' => {
                artifact => 1,
                'sdam'   => 'd8',
                'ldam'   => 'd12',
                'tohit'  => 'd5',
                'hands'  => 1,
                'weight' => 40,
                'type'   => 'iron',
            },
            'Giantslayer' => {
                artifact => 1,
                'sdam'   => 'd8',
                'ldam'   => 'd12',
                'tohit'  => 'd5',
                'hands'  => 1,
                'weight' => 40,
                'type'   => 'iron',
            },
            'Grayswandir' => {
                artifact => 1,
                'sdam'   => 'd8',
                'ldam'   => 'd8',
                'tohit'  => 'd5',
                'hands'  => 1,
                'weight' => 40,
                'type'   => 'silver',
            },
            'Grimtooth' => {
                artifact => 1,
                'sdam'   => 'd6+d3',
                'ldam'   => 'd6+d3',
                'tohit'  => 'd2+2',
                'hands'  => 1,
                'weight' => 10,
                'type'   => 'iron',
            },
            'Longbow of Diana' => {
                artifact => 1,
                'sdam'   => 'd2',
                'ldam'   => 'd2',
                'tohit'  => 'd5',
                'hands'  => 1,
                'weight' => 30,
                'type'   => 'wood',
            },
            'Magicbane' => {
                artifact => 1,
                'sdam'   => '2d4',
                'ldam'   => 'd4+d3',
                'tohit'  => 'd5+2',
                'hands'  => 1,
                'weight' => 10,
                'type'   => 'iron',
            },
            'Mjollnir' => {
                artifact => 1,
                'sdam'   => 'd4+1',
                'ldam'   => 'd4',
                'tohit'  => 'd5',
                'hands'  => 1,
                'weight' => 50,
                'type'   => 'iron',
            },
            'Ogresmasher' => {
                artifact => 1,
                'sdam'   => 'd4+1',
                'ldam'   => 'd4',
                'tohit'  => 'd5',
                'hands'  => 1,
                'weight' => 50,
                'type'   => 'iron',
            },
            'Orcrist' => {
                artifact => 1,
                'sdam'   => 'd6+d4',
                'ldam'   => 'd6+1',
                'tohit'  => 'd5',
                'hands'  => 1,
                'weight' => 70,
                'type'   => 'wood',
            },
            'Sceptre of Might' => {
                artifact => 1,
                'sdam'   => 'd6+1',
                'ldam'   => 'd6',
                'tohit'  => 'd5',
                'hands'  => 1,
                'weight' => 30,
                'type'   => 'iron',
            },
            'Snickersnee' => {
                artifact => 1,
                'sdam'   => 'd10+d8',
                'ldam'   => 'd12+d8',
                'tohit'  => '1',
                'hands'  => 1,
                'weight' => 40,
                'type'   => 'iron',
            },
            'Staff of Aesculapius' => {
                artifact => 1,
                'sdam'   => 'd6',
                'ldam'   => 'd6',
                'tohit'  => '0',
                'hands'  => 2,
                'weight' => 40,
                'type'   => 'wood',
            },
            'Sting' => {
                artifact => 1,
                'sdam'   => 'd5',
                'ldam'   => 'd3',
                'tohit'  => 'd5+2',
                'hands'  => 1,
                'weight' => 10,
                'type'   => 'wood',
            },
            'Stormbringer' => {
                artifact => 1,
                'sdam'   => '2d4+d2',
                'ldam'   => 'd6+d2+1',
                'tohit'  => 'd5',
                'hands'  => 1,
                'weight' => 40,
                'type'   => 'iron',
            },
            'Sunsword' => {
                artifact => 1,
                'sdam'   => 'd8',
                'ldam'   => 'd12',
                'tohit'  => 'd5',
                'hands'  => 1,
                'weight' => 40,
                'type'   => 'iron',
            },
            'The Tsurugi of Muramasa' => {
                artifact => 1,
                'sdam'   => 'd16+d8',
                'ldam'   => '2d8+2d6',
                'tohit'  => '2',
                'hands'  => 2,
                'weight' => 60,
                'type'   => 'metal',
            },
            'Trollsbane' => {
                artifact => 1,
                'sdam'   => '2d4',
                'ldam'   => 'd6+1',
                'tohit'  => 'd5',
                'hands'  => 1,
                'weight' => 120,
                'type'   => 'iron',
            },
            'Vorpal Blade' => {
                artifact => 1,
                'sdam'   => 'd8+1',
                'ldam'   => 'd12+1',
                'tohit'  => 'd5',
                'hands'  => 1,
                'weight' => 40,
                'type'   => 'iron',
            },
            'Werebane' => {
                artifact => 1,
                'sdam'   => 'd8',
                'ldam'   => 'd8',
                'tohit'  => 'd2',
                'hands'  => 1,
                'weight' => 40,
                'type'   => 'silver',
            },
            'aklys' => {
                'sdam'   => 'd6',
                'ldam'   => 'd3',
                'tohit'  => '0',
                'hands'  => 1,
                'weight' => 15,
                'type'   => 'iron',
            },
            'arrow' => {
                'sdam'   => 'd6',
                'ldam'   => 'd6',
                'tohit'  => '0',
                'hands'  => 1,
                'weight' => 1,
                'type'   => 'iron',
            },
            'athame' => {
                'sdam'   => 'd4',
                'ldam'   => 'd3',
                'tohit'  => '2',
                'hands'  => 1,
                'weight' => 10,
                'type'   => 'iron',
            },
            'axe' => {
                'sdam'   => 'd6',
                'ldam'   => 'd4',
                'tohit'  => '0',
                'hands'  => 1,
                'weight' => 60,
                'type'   => 'iron',
            },
            'bardiche' => {
                'sdam'   => '2d4',
                'ldam'   => '3d4',
                'tohit'  => '0',
                'hands'  => 2,
                'weight' => 120,
                'type'   => 'iron',
            },
            'bare-handed combat' => {
                'sdam'   => 'd2',
                'ldam'   => 'd2',
                'tohit'  => '0',
                'type'   => 'none',
            },
            'battle-axe' => {
                'sdam'   => 'd8+d4',
                'ldam'   => 'd6+2d4',
                'tohit'  => '0',
                'hands'  => 2,
                'weight' => 120,
                'type'   => 'iron',
            },
            'bec-de-corbin' => {
                'sdam'   => 'd8',
                'ldam'   => 'd6',
                'tohit'  => '0',
                'hands'  => 2,
                'weight' => 100,
                'type'   => 'iron',
            },
            'bill-guisarme' => {
                'sdam'   => '2d4',
                'ldam'   => 'd10',
                'tohit'  => '0',
                'hands'  => 2,
                'weight' => 120,
                'type'   => 'iron',
            },
            'boomerang' => {
                'sdam'   => 'd9',
                'ldam'   => 'd9',
                'tohit'  => '0',
                'hands'  => 1,
                'weight' => 5,
                'type'   => 'wood',
            },
            'bow' => {
                'sdam'   => 'd2',
                'ldam'   => 'd2',
                'tohit'  => '0',
                'hands'  => 1,
                'weight' => 30,
                'type'   => 'wood',
            },
            'broadsword' => {
                'sdam'   => '2d4',
                'ldam'   => 'd6+1',
                'tohit'  => '0',
                'hands'  => 1,
                'weight' => 70,
                'type'   => 'iron',
            },
            'bullwhip' => {
                'sdam'   => 'd2',
                'ldam'   => '1',
                'tohit'  => '0',
                'hands'  => 1,
                'weight' => 20,
                'type'   => 'leather',
            },
            'club' => {
                'sdam'   => 'd6',
                'ldam'   => 'd3',
                'tohit'  => '0',
                'hands'  => 1,
                'weight' => 30,
                'type'   => 'wood',
            },
            'crossbow' => {
                'sdam'   => 'd2',
                'ldam'   => 'd2',
                'tohit'  => '0',
                'hands'  => 1,
                'weight' => 50,
                'type'   => 'wood',
            },
            'crossbow bolt' => {
                'sdam'   => 'd4+1',
                'ldam'   => 'd6+1',
                'tohit'  => '0',
                'hands'  => 1,
                'weight' => 1,
                'type'   => 'iron',
            },
            'crysknife' => {
                'sdam'   => 'd10',
                'ldam'   => 'd10',
                'tohit'  => '3',
                'hands'  => 1,
                'weight' => 20,
                'type'   => 'mineral',
            },
            'dagger' => {
                'sdam'   => 'd4',
                'ldam'   => 'd3',
                'tohit'  => '2',
                'hands'  => 1,
                'weight' => 10,
                'type'   => 'iron',
            },
            'dart' => {
                'sdam'   => 'd3',
                'ldam'   => 'd2',
                'tohit'  => '0',
                'hands'  => 1,
                'weight' => 1,
                'type'   => 'iron',
            },
            'dwarvish mattock' => {
                'sdam'   => 'd12',
                'ldam'   => 'd8+2d6',
                'tohit'  => '-1',
                'hands'  => 2,
                'weight' => 120,
                'type'   => 'iron',
            },
            'dwarvish short sword' => {
                'sdam'   => 'd7',
                'ldam'   => 'd8',
                'tohit'  => '0',
                'hands'  => 1,
                'weight' => 30,
                'type'   => 'iron',
            },
            'dwarvish spear' => {
                'sdam'   => 'd8',
                'ldam'   => 'd8',
                'tohit'  => '0',
                'hands'  => 1,
                'weight' => 35,
                'type'   => 'iron',
            },
            'elven arrow' => {
                'sdam'   => 'd7',
                'ldam'   => 'd6',
                'tohit'  => '0',
                'hands'  => 1,
                'weight' => 1,
                'type'   => 'wood',
            },
            'elven bow' => {
                'sdam'   => 'd2',
                'ldam'   => 'd2',
                'tohit'  => '0',
                'hands'  => 1,
                'weight' => 30,
                'type'   => 'wood',
            },
            'elven broadsword' => {
                'sdam'   => 'd6+d4',
                'ldam'   => 'd6+1',
                'tohit'  => '0',
                'hands'  => 1,
                'weight' => 70,
                'type'   => 'wood',
            },
            'elven dagger' => {
                'sdam'   => 'd5',
                'ldam'   => 'd3',
                'tohit'  => '2',
                'hands'  => 1,
                'weight' => 10,
                'type'   => 'wood',
            },
            'elven short sword' => {
                'sdam'   => 'd8',
                'ldam'   => 'd8',
                'tohit'  => '0',
                'hands'  => 1,
                'weight' => 30,
                'type'   => 'wood',
            },
            'elven spear' => {
                'sdam'   => 'd7',
                'ldam'   => 'd8',
                'tohit'  => '0',
                'hands'  => 1,
                'weight' => 30,
                'type'   => 'wood',
            },
            'fauchard' => {
                'sdam'   => 'd6',
                'ldam'   => 'd8',
                'tohit'  => '0',
                'hands'  => 2,
                'weight' => 60,
                'type'   => 'iron',
            },
            'flail' => {
                'sdam'   => 'd6+1',
                'ldam'   => '2d4',
                'tohit'  => '0',
                'hands'  => 1,
                'weight' => 15,
                'type'   => 'iron',
            },
            'flintstone' => {
                'sdam'   => 'd6',
                'ldam'   => 'd6',
                'tohit'  => '0',
                'hands'  => 1,
                'weight' => 10,
                'type'   => 'mineral',
            },
            'glaive' => {
                'sdam'   => 'd6',
                'ldam'   => 'd10',
                'tohit'  => '0',
                'hands'  => 2,
                'weight' => 75,
                'type'   => 'iron',
            },
            'grappling hook' => {
                'sdam'   => 'd2',
                'ldam'   => 'd6',
                'tohit'  => '0',
                'hands'  => 1,
                'weight' => 30,
                'type'   => 'iron',
            },
            'guisarme' => {
                'sdam'   => '2d4',
                'ldam'   => 'd8',
                'tohit'  => '0',
                'hands'  => 2,
                'weight' => 80,
                'type'   => 'iron',
            },
            'halberd' => {
                'sdam'   => 'd10',
                'ldam'   => '2d6',
                'tohit'  => '0',
                'hands'  => 2,
                'weight' => 150,
                'type'   => 'iron',
            },
            'javelin' => {
                'sdam'   => 'd6',
                'ldam'   => 'd6',
                'tohit'  => '0',
                'hands'  => 1,
                'weight' => 20,
                'type'   => 'iron',
            },
            'katana' => {
                'sdam'   => 'd10',
                'ldam'   => 'd12',
                'tohit'  => '1',
                'hands'  => 1,
                'weight' => 40,
                'type'   => 'iron',
            },
            'knife' => {
                'sdam'   => 'd3',
                'ldam'   => 'd2',
                'tohit'  => '0',
                'hands'  => 1,
                'weight' => 5,
                'type'   => 'iron',
            },
            'lance' => {
                'sdam'   => 'd6',
                'ldam'   => 'd8',
                'tohit'  => '0',
                'hands'  => 1,
                'weight' => 180,
                'type'   => 'iron',
            },
            'long sword' => {
                'sdam'   => 'd8',
                'ldam'   => 'd12',
                'tohit'  => '0',
                'hands'  => 1,
                'weight' => 40,
                'type'   => 'iron',
            },
            'lucern hammer' => {
                'sdam'   => '2d4',
                'ldam'   => 'd6',
                'tohit'  => '0',
                'hands'  => 2,
                'weight' => 150,
                'type'   => 'iron',
            },
            'mace' => {
                'sdam'   => 'd6+1',
                'ldam'   => 'd6',
                'tohit'  => '0',
                'hands'  => 1,
                'weight' => 30,
                'type'   => 'iron',
            },
            'martial arts' => {
                'sdam'   => 'd4',
                'ldam'   => 'd4',
                'tohit'  => '0',
                'hands'  => 1,
                'weight' => 40,
                'type'   => 'none',
            },
            'morning star' => {
                'sdam'   => '2d4',
                'ldam'   => 'd6+1',
                'tohit'  => '0',
                'hands'  => 1,
                'weight' => 120,
                'type'   => 'iron',
            },
            'orcish arrow' => {
                'sdam'   => 'd5',
                'ldam'   => 'd6',
                'tohit'  => '0',
                'hands'  => 1,
                'weight' => 1,
                'type'   => 'iron',
            },
            'orcish bow' => {
                'sdam'   => 'd2',
                'ldam'   => 'd2',
                'tohit'  => '0',
                'hands'  => 1,
                'weight' => 30,
                'type'   => 'wood',
            },
            'orcish dagger' => {
                'sdam'   => 'd3',
                'ldam'   => 'd3',
                'tohit'  => '2',
                'hands'  => 1,
                'weight' => 10,
                'type'   => 'iron',
            },
            'orcish short sword' => {
                'sdam'   => 'd5',
                'ldam'   => 'd8',
                'tohit'  => '0',
                'hands'  => 1,
                'weight' => 30,
                'type'   => 'iron',
            },
            'orcish spear' => {
                'sdam'   => 'd5',
                'ldam'   => 'd8',
                'tohit'  => '0',
                'hands'  => 1,
                'weight' => 30,
                'type'   => 'iron',
            },
            'partisan' => {
                'sdam'   => 'd6',
                'ldam'   => 'd6+1',
                'tohit'  => '0',
                'hands'  => 2,
                'weight' => 80,
                'type'   => 'iron',
            },
            'pick-axe' => {
                'sdam'   => 'd6',
                'ldam'   => 'd3',
                'tohit'  => '0',
                'hands'  => 1,
                'weight' => 100,
                'type'   => 'iron',
            },
            'quarterstaff' => {
                'sdam'   => 'd6',
                'ldam'   => 'd6',
                'tohit'  => '0',
                'hands'  => 2,
                'weight' => 40,
                'type'   => 'wood',
            },
            'ranseur' => {
                'sdam'   => '2d4',
                'ldam'   => '2d4',
                'tohit'  => '0',
                'hands'  => 2,
                'weight' => 50,
                'type'   => 'iron',
            },
            'rocks/gems/glass' => {
                'sdam'   => 'd3',
                'ldam'   => 'd3',
                'tohit'  => '0',
                'hands'  => 1,
                'weight' => 40,
                'type'   => 'vary',
            },
            'rubber hose' => {
                'sdam'   => 'd4',
                'ldam'   => 'd3',
                'tohit'  => '0',
                'hands'  => 1,
                'weight' => 20,
                'type'   => 'plastic',
            },
            'runesword' => {
                'sdam'   => '2d4',
                'ldam'   => 'd6+1',
                'tohit'  => '0',
                'hands'  => 1,
                'weight' => 40,
                'type'   => 'iron',
            },
            'scalpel' => {
                'sdam'   => 'd3',
                'ldam'   => 'd3',
                'tohit'  => '2',
                'hands'  => 1,
                'weight' => 5,
                'type'   => 'metal',
            },
            'scimitar' => {
                'sdam'   => 'd8',
                'ldam'   => 'd8',
                'tohit'  => '0',
                'hands'  => 1,
                'weight' => 40,
                'type'   => 'iron',
            },
            'short sword' => {
                'sdam'   => 'd6',
                'ldam'   => 'd8',
                'tohit'  => '0',
                'hands'  => 1,
                'weight' => 30,
                'type'   => 'iron',
            },
            'shuriken' => {
                'sdam'   => 'd8',
                'ldam'   => 'd6',
                'tohit'  => '2',
                'hands'  => 1,
                'weight' => 1,
                'type'   => 'iron',
            },
            'silver arrow' => {
                'sdam'   => 'd6',
                'ldam'   => 'd6',
                'tohit'  => '0',
                'hands'  => 1,
                'weight' => 1,
                'type'   => 'silver',
            },
            'silver dagger' => {
                'sdam'   => 'd4',
                'ldam'   => 'd3',
                'tohit'  => '2',
                'hands'  => 1,
                'weight' => 12,
                'type'   => 'silver',
            },
            'silver saber' => {
                'sdam'   => 'd8',
                'ldam'   => 'd8',
                'tohit'  => '0',
                'hands'  => 1,
                'weight' => 40,
                'type'   => 'silver',
            },
            'silver spear' => {
                'sdam'   => 'd6',
                'ldam'   => 'd8',
                'tohit'  => '0',
                'hands'  => 1,
                'weight' => 36,
                'type'   => 'silver',
            },
            'sling' => {
                'sdam'   => 'd2',
                'ldam'   => 'd2',
                'tohit'  => '0',
                'hands'  => 1,
                'weight' => 3,
                'type'   => 'leather',
            },
            'spear' => {
                'sdam'   => 'd6',
                'ldam'   => 'd8',
                'tohit'  => '0',
                'hands'  => 1,
                'weight' => 30,
                'type'   => 'iron',
            },
            'spetum' => {
                'sdam'   => 'd6+1',
                'ldam'   => '2d6',
                'tohit'  => '0',
                'hands'  => 2,
                'weight' => 50,
                'type'   => 'iron',
            },
            'stiletto' => {
                'sdam'   => 'd3',
                'ldam'   => 'd2',
                'tohit'  => '0',
                'hands'  => 1,
                'weight' => 5,
                'type'   => 'iron',
            },
            'trident' => {
                'sdam'   => 'd6+1',
                'ldam'   => '3d4',
                'tohit'  => '0',
                'hands'  => 1,
                'weight' => 25,
                'type'   => 'iron',
            },
            'tsurugi' => {
                'sdam'   => 'd16',
                'ldam'   => 'd8+2d6',
                'tohit'  => '2',
                'hands'  => 2,
                'weight' => 60,
                'type'   => 'metal',
            },
            'two-handed sword' => {
                'sdam'   => 'd12',
                'ldam'   => '3d6',
                'tohit'  => '0',
                'hands'  => 2,
                'weight' => 150,
                'type'   => 'iron',
            },
            'unicorn horn' => {
                'sdam'   => 'd12',
                'ldam'   => 'd12',
                'tohit'  => '1',
                'hands'  => 2,
                'weight' => 20,
                'type'   => 'bone',
            },
            'voulge' => {
                'sdam'   => '2d4',
                'ldam'   => '2d4',
                'tohit'  => '0',
                'hands'  => 2,
                'weight' => 125,
                'type'   => 'iron',
            },
            'war hammer' => {
                'sdam'   => 'd4+1',
                'ldam'   => 'd4',
                'tohit'  => '0',
                'hands'  => 1,
                'weight' => 50,
                'type'   => 'iron',
            },
            'worm tooth' => {
                'sdam'   => 'd2',
                'ldam'   => 'd2',
                'tohit'  => '0',
                'hands'  => 1,
                'weight' => 20,
                'type'   => 'none',
            },
            'ya' => {
                'sdam'   => 'd7',
                'ldam'   => 'd7',
                'tohit'  => '1',
                'hands'  => 1,
                'weight' => 1,
                'type'   => 'metal',
            },
            'yumi' => {
                'sdam'   => 'd2',
                'ldam'   => 'd2',
                'tohit'  => '0',
                'hands'  => 1,
                'weight' => 30,
                'type'   => 'wood',
            },
        };

        # Japanese name mappings
        $weapons->{'wakizashi'} = $weapons->{'short sword'};
        $weapons->{'ninja-to'}  = $weapons->{'broadsword'};
        $weapons->{'nunchaku'}  = $weapons->{'flail'};
        $weapons->{'naginata'}  = $weapons->{'glaive'};
        $weapons->{'shito'}     = $weapons->{'knife'};

        # tag each weapon with its name
        while (my ($name, $stats) = each %$tools) {
            $stats->{name} = $name;
            $stats->{appearance} = $name unless $stats->{appearance};
        }

        return $weapons;
    },
);

sub weapon {
    my $self = shift;
    my $arg  = shift;
    return $self->list->{$arg};
}

1;

