#!perl -T
use TAEB::Test::Items (
    ["a - a +1 club",
     {is_greased => 0, is_poisoned => 0, erosion1 => 0, erosion2 => 0,
      is_fooproof => 0}],
    ["m - a blessed +4 long sword",
     {is_greased => 0, is_poisoned => 0, erosion1 => 0, erosion2 => 0,
      is_fooproof => 0}],
    ["s - a poisoned +0 arrow",
     {is_greased => 0, is_poisoned => 1, erosion1 => 0, erosion2 => 0,
      is_fooproof => 0}],
    ["C - a poisoned rusty +0 arrow",
     {is_greased => 0, is_poisoned => 1, erosion1 => 1, erosion2 => 0,
      is_fooproof => 0}],
    ["D - a poisoned very rusty corroded +0 arrow",
     {is_greased => 0, is_poisoned => 1, erosion1 => 2, erosion2 => 1,
      is_fooproof => 0}],
    ["E - a blessed poisoned rusty thoroughly corroded +1 arrow",
     {is_greased => 0, is_poisoned => 1, erosion1 => 1, erosion2 => 3,
      is_fooproof => 0}],
    ["F - a blessed greased poisoned rusty corroded +2 arrow",
     {is_greased => 1, is_poisoned => 1, erosion1 => 1, erosion2 => 1,
      is_fooproof => 0}],
    ["e - an uncursed rotted fireproof +0 leather armor (being worn)",
     {is_greased => 0, erosion1 => 0, erosion2 => 1, is_fooproof => 1}],
    ["t - an uncursed greased partly used tallow candle (lit)",
     {is_greased => 1, erosion1 => 0, erosion2 => 0, is_fooproof => 0,
      is_partly_used => 1}],
    ["v - an uncursed burnt rotted partly used candle",
     {is_greased => 0, erosion1 => 1, erosion2 => 1, is_fooproof => 0,
      is_partly_used => 1}],
    ["f - an uncursed diluted smoky potion",
     {is_greased => 0, is_diluted => 1}],
    ["h - an uncursed partly eaten food ration",
     {is_greased => 0, is_partly_eaten => 1}],
);
