#!perl -T
use TAEB::Test::Items (
    ["a - a blessed +1 quarterstaff (weapon in hands) (unpaid, 15 zorkmids)",
     {price => 15}],
    ["p - a +0 studded leather armor (being worn) (unpaid, 15 zorkmids)",
     {price => 15}],
    ["x - 11 arrows (in quiver) (unpaid, 22 zorkmids)",
     {price => 22}],
    ["B - a tin (unpaid, 5 zorkmids)",
     {price => 5}],
    ["o - an uncursed triangular amulet (being worn) (unpaid, 150 zorkmids)",
     {price => 150}],
    ["d - an uncursed brass ring (on right hand) (unpaid, 100 zorkmids)",
     {price => 100}],
    ["c - a runed wand (unpaid, 200 zorkmids)",
     {price => 200}],
    ["I - a lamp (lit) (unpaid, 10 zorkmids)",
     {price => 10}],
    ["z - a yellow gem (unpaid, 1500 zorkmids)",
     {price => 1500}],
    ["H - a partly used candle",
     {price => 0}],
);
